version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - COMMANDS_JWT_ISSUER=${COMMANDS_JWT_ISSUER}
      - COMMANDS_JWT_AUDIENCE=${COMMANDS_JWT_AUDIENCE}
      - COMMANDS_API_URL=https://api.commands.com
      - LOG_LEVEL=${LOG_LEVEL:-info}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: mcp-network